#include<bits/stdc++.h>
using namespace std;

struct Village {
    double x;
    double y;
    int n;
};

struct Helicopter_info {
    int home_city;
    double w_cap, dcap, F, alpha;
};

struct Delivery {
    int village;
    int d, p, o; // packets dropped
};

struct Trip {
    vector<Delivery> stops;   // villages visited in order
    double distance;          // cached route length
    double value;             // cached total value
    double weight;            // total carried weight
};

struct Helicopter {
    vector<Trip> trips;       // all trips (some may be empty)
    double total_distance;    // sum of trip distances
};

struct State {
    vector<Helicopter> helis; 
    vector<array<int,3>> delivered; // per-village totals (d,p,o)
    double objective;         // cached objective value
};

// Global variables for problem parameters
double DMax;
double w_d, v_d, w_p, v_p, w_o, v_o;
vector<pair<double, double>> cities;
vector<Village> villages;
vector<Helicopter_info> helis;
int C, V, H;

double calculate_distance(pair<double, double> p1, pair<double, double> p2) {
    return sqrt((p1.first - p2.first) * (p1.first - p2.first) + 
                (p1.second - p2.second) * (p1.second - p2.second));
}

// Calculate the total distance for a trip route (home -> villages -> home)
double calculate_trip_distance(int heli_id, const Trip& trip) {
    if (trip.stops.empty()) return 0.0;
    
    double total_dist = 0.0;
    pair<double, double> current_pos = cities[helis[heli_id].home_city - 1]; // Start at home city (1-indexed)
    
    // Visit each village in order
    for (const Delivery& delivery : trip.stops) {
        pair<double, double> village_pos = {villages[delivery.village - 1].x, villages[delivery.village - 1].y}; // 1-indexed
        total_dist += calculate_distance(current_pos, village_pos);
        current_pos = village_pos;
    }
    
    // Return to home city
    total_dist += calculate_distance(current_pos, cities[helis[heli_id].home_city - 1]);
    
    return total_dist;
}

// Calculate the total weight of packages carried in a trip
double calculate_trip_weight(const Trip& trip) {
    if (trip.stops.empty()) return 0.0;
    
    double max_weight = 0.0;
    map<int, array<int,3>> remaining_to_deliver;
    
    // First pass: calculate total packages to pick up
    for (const Delivery& delivery : trip.stops) {
        remaining_to_deliver[delivery.village][0] += delivery.d;
        remaining_to_deliver[delivery.village][1] += delivery.p;
        remaining_to_deliver[delivery.village][2] += delivery.o;
    }
    
    array<int,3> current_load = {0, 0, 0};
    
    // Calculate initial load (total packages to carry)
    for (const auto& pair : remaining_to_deliver) {
        current_load[0] += pair.second[0];
        current_load[1] += pair.second[1];
        current_load[2] += pair.second[2];
    }
    
    double current_weight = current_load[0] * w_d + current_load[1] * w_p + current_load[2] * w_o;
    max_weight = max(max_weight, current_weight);
    
    // Simulate the trip to find maximum weight carried
    for (const Delivery& delivery : trip.stops) {
        // Drop packages at this village
        current_load[0] -= delivery.d;
        current_load[1] -= delivery.p;
        current_load[2] -= delivery.o;
        
        current_weight = current_load[0] * w_d + current_load[1] * w_p + current_load[2] * w_o;
        max_weight = max(max_weight, current_weight);
    }
    
    return max_weight;
}

// Calculate the value generated by a trip
double calculate_trip_value(const Trip& trip) {
    double trip_value = 0.0;
    
    for (const Delivery& delivery : trip.stops) {
        trip_value += delivery.d * v_d + delivery.p * v_p + delivery.o * v_o;
    }
    
    return trip_value;
}

// Fill all Trip fields (distance, weight, value)
void fill_trip_data(int heli_id, Trip& trip) {
    trip.distance = calculate_trip_distance(heli_id, trip);
    trip.weight = calculate_trip_weight(trip);
    trip.value = calculate_trip_value(trip);
}

// Fill helicopter total_distance
void fill_helicopter_data(Helicopter& heli) {
    heli.total_distance = 0.0;
    for (const Trip& trip : heli.trips) {
        heli.total_distance += trip.distance;
    }
}

// Fill the delivered array with totals per village
void fill_delivered_totals(State& state) {
    // Initialize delivered array
    state.delivered.assign(V, {0, 0, 0});
    
    // Sum up deliveries from all helicopters and trips
    for (const Helicopter& heli : state.helis) {
        for (const Trip& trip : heli.trips) {
            for (const Delivery& delivery : trip.stops) {
                state.delivered[delivery.village - 1][0] += delivery.d; // Convert to 0-indexed
                state.delivered[delivery.village - 1][1] += delivery.p;
                state.delivered[delivery.village - 1][2] += delivery.o;
            }
        }
    }
}

double obj_func(State& state) {
    // Fill all missing data
    for (int h = 0; h < H; h++) {
        for (Trip& trip : state.helis[h].trips) {
            fill_trip_data(h, trip);
        }
        fill_helicopter_data(state.helis[h]);
    }
    
    fill_delivered_totals(state);
    
    double total_value = 0.0;
    double total_cost = 0.0;
    
    // Check feasibility constraints first
    for (int h = 0; h < H; h++) {
        const Helicopter& heli = state.helis[h];
        
        // Check if total distance exceeds DMax
        if (heli.total_distance > DMax + 1e-9) {
            state.objective = -INFINITY;
            return -INFINITY; // Infeasible
        }
        
        for (const Trip& trip : heli.trips) {
            if (trip.stops.empty()) continue; // Skip empty trips
            
            // Check weight capacity constraint
            if (trip.weight > helis[h].w_cap + 1e-9) {
                state.objective = -INFINITY;
                return -INFINITY; // Infeasible
            }
            
            // Check distance capacity constraint per trip
            if (trip.distance > helis[h].dcap + 1e-9) {
                state.objective = -INFINITY;
                return -INFINITY; // Infeasible
            }
            
            // Add trip cost
            total_cost += helis[h].F + helis[h].alpha * trip.distance;
        }
    }
    
    // Calculate total value from deliveries
    for (int v_idx = 0; v_idx < V; v_idx++) {
        int people = villages[v_idx].n;
        int food_limit = 9 * people; // Maximum useful food packets
        
        // Calculate food delivered (d + p)
        int total_food = state.delivered[v_idx][0] + state.delivered[v_idx][1];
        int useful_food = min(total_food, food_limit);
        
        // Calculate value from food (prioritize perishable over dry)
        int perishable = state.delivered[v_idx][1];
        int dry = state.delivered[v_idx][0];
        
        if (useful_food <= perishable) {
            // All useful food is perishable
            total_value += useful_food * v_p; // perishable value
        } else {
            // Use all perishable + some dry
            total_value += perishable * v_p; // all perishable
            total_value += (useful_food - perishable) * v_d; // remaining as dry
        }
        
        // Add value from other supplies (no limit specified in problem)
        total_value += state.delivered[v_idx][2] * v_o;
    }
    
    // Calculate objective = total_value - total_cost
    state.objective = total_value - total_cost;
    
    return state.objective;
}

int main(){
    double time;
    cin >> time;

    cin >> DMax;

    cin >> w_d >> v_d >> w_p >> v_p >> w_o >> v_o;

    cin >> C;
    cities.resize(C);
    for (int i = 0; i < C; ++i) {
        double x, y;
        cin >> x >> y;
        cities[i] = {x, y};
    }

    cin >> V;
    villages.resize(V);
    for (int i = 0; i < V; ++i) {
        double x, y;
        int n;
        cin >> x >> y >> n;
        villages[i] = {x, y, n};
    }

    cin >> H;
    helis.resize(H);
    for (int i = 0; i < H; ++i) {
        int home_city;
        double wcap, dcap, F, alpha;
        cin >> home_city >> wcap >> dcap >> F >> alpha;
        helis[i] = {home_city, wcap, dcap, F, alpha};
    }

    // Example usage:
    State test_state;
    test_state.helis.resize(H);
    
    // Initialize with empty trips
    for (int h = 0; h < H; h++) {
        test_state.helis[h].trips.clear();
        test_state.helis[h].total_distance = 0.0;
    }
    
    // Calculate objective (this will fill all the missing fields)
    double result = obj_func(test_state);
    cout << "Objective value: " << result << endl;

    return 0;
}