#include <iostream>
#include <vector>
#include <array>
#include <map>
#include <cmath>
#include <algorithm>
#include <ctime>
#include <random>

using namespace std;

struct Village {
    double x;
    double y;
    int n;
};

struct Helicopter_info {
    int home_city;
    double w_cap, dcap, F, alpha;
};

struct Delivery {
    int village;
    int d, p, o; // packets dropped
};

struct Trip {
    vector<Delivery> stops;   // villages visited in order
    double distance;          // cached route length
    double value;             // cached total value
    double weight;            // total carried weight
};

struct Helicopter {
    vector<Trip> trips;       // all trips (some may be empty)
    double total_distance;    // sum of trip distances
};

struct State {
    vector<Helicopter> helis; 
    vector<array<int,3>> delivered; // per-village totals (d,p,o)
    double objective;         // cached objective value
};

// Global variables for problem parameters
double DMax;
double w_d, v_d, w_p, v_p, w_o, v_o;
vector<pair<double, double>> cities;
vector<Village> villages;
vector<Helicopter_info> helis;
std::vector<std::vector<double>> dist_matrix;
int C, V, H;

double calculate_distance(pair<double, double> p1, pair<double, double> p2) {
    return sqrt((p1.first - p2.first) * (p1.first - p2.first) + 
                (p1.second - p2.second) * (p1.second - p2.second));
}

void precompute_distances() {
    int total_nodes = C + V;
    dist_matrix.assign(total_nodes, std::vector<double>(total_nodes, 0.0));
    std::vector<std::pair<double, double>> points;
    points.insert(points.end(), cities.begin(), cities.end());
    for(const auto& v : villages) {
        points.push_back({v.x, v.y});
    }
    for (int i = 0; i < total_nodes; ++i) {
        for (int j = i; j < total_nodes; ++j) {
            double d = calculate_distance(points[i], points[j]);
            dist_matrix[i][j] = d;
            dist_matrix[j][i] = d;
        }
    }
}

// Calculate the total distance for a trip route (home -> villages -> home)
double calculate_trip_distance(int heli_id, const Trip& trip) {
    if (trip.stops.empty()) return 0.0;
    
    double total_dist = 0.0;
    pair<double, double> current_pos = cities[helis[heli_id].home_city - 1]; // Start at home city (1-indexed)
    
    // Visit each village in order
    for (const Delivery& delivery : trip.stops) {
        pair<double, double> village_pos = {villages[delivery.village - 1].x, villages[delivery.village - 1].y}; // 1-indexed
        total_dist += calculate_distance(current_pos, village_pos);
        current_pos = village_pos;
    }
    
    // Return to home city
    total_dist += calculate_distance(current_pos, cities[helis[heli_id].home_city - 1]);
    
    return total_dist;
}

double calculate_trip_weight(const Trip& trip) {
    if (trip.stops.empty()) return 0.0;

    long long total_d = 0, total_p = 0, total_o = 0;

    for (const Delivery& delivery : trip.stops) {
        total_d += delivery.d;
        total_p += delivery.p;
        total_o += delivery.o;
    }

    return total_d * w_d + total_p * w_p + total_o * w_o;
}


// Calculate the value generated by a trip
double calculate_trip_value(const Trip& trip) {
    double trip_value = 0.0;
    
    for (const Delivery& delivery : trip.stops) {
        trip_value += delivery.d * v_d + delivery.p * v_p + delivery.o * v_o;
    }
    
    return trip_value;
}

// Fill all Trip fields (distance, weight, value)
void fill_trip_data(int heli_id, Trip& trip) {
    trip.distance = calculate_trip_distance(heli_id, trip);
    trip.weight = calculate_trip_weight(trip);
    trip.value = calculate_trip_value(trip);
}

// Fill helicopter total_distance
void fill_helicopter_data(Helicopter& heli) {
    heli.total_distance = 0.0;
    for (const Trip& trip : heli.trips) {
        heli.total_distance += trip.distance;
    }
}

// Fill the delivered array with totals per village
void fill_delivered_totals(State& state) {
    // Initialize delivered array
    state.delivered.assign(V, {0, 0, 0});
    
    // Sum up deliveries from all helicopters and trips
    for (const Helicopter& heli : state.helis) {
        for (const Trip& trip : heli.trips) {
            for (const Delivery& delivery : trip.stops) {
                state.delivered[delivery.village - 1][0] += delivery.d; // Convert to 0-indexed
                state.delivered[delivery.village - 1][1] += delivery.p;
                state.delivered[delivery.village - 1][2] += delivery.o;
            }
        }
    }
}

double obj_func(State& state) {
    // Fill all missing data
    for (int h = 0; h < H; h++) {
        for (Trip& trip : state.helis[h].trips) {
            fill_trip_data(h, trip);
        }
        fill_helicopter_data(state.helis[h]);
    }
    
    fill_delivered_totals(state);
    
    double total_value = 0.0;
    double total_cost = 0.0;
    
    // Check feasibility constraints first
    for (int h = 0; h < H; h++) {
        const Helicopter& heli = state.helis[h];
        
        // Check if total distance exceeds DMax
        if (heli.total_distance > DMax + 1e-9) {
            state.objective = -INFINITY;
            return -INFINITY; // Infeasible
        }
        
        for (const Trip& trip : heli.trips) {
            if (trip.stops.empty()) continue; // Skip empty trips
            
            // Check weight capacity constraint
            if (trip.weight > helis[h].w_cap + 1e-9) {
                state.objective = -INFINITY;
                return -INFINITY; // Infeasible
            }
            
            // Check distance capacity constraint per trip
            if (trip.distance > helis[h].dcap + 1e-9) {
                state.objective = -INFINITY;
                return -INFINITY; // Infeasible
            }
            
            // Add trip cost
            total_cost += helis[h].F + helis[h].alpha * trip.distance;
        }
    }
    
    // Calculate total value from deliveries
    for (int v_idx = 0; v_idx < V; v_idx++) {
        int people = villages[v_idx].n;
        int food_limit = 9 * people; // Maximum useful food packets
        
        // Calculate food delivered (d + p)
        int total_food = state.delivered[v_idx][0] + state.delivered[v_idx][1];
        int useful_food = min(total_food, food_limit);
        
        // Calculate value from food (prioritize perishable over dry)
        int perishable = state.delivered[v_idx][1];
        int dry = state.delivered[v_idx][0];
        
        if (useful_food <= perishable) {
            // All useful food is perishable
            total_value += useful_food * v_p; // perishable value
        } else {
            // Use all perishable + some dry
            total_value += perishable * v_p; // all perishable
            total_value += (useful_food - perishable) * v_d; // remaining as dry
        }
        
        // Add value from other supplies (capped at number of people)
        total_value += min(state.delivered[v_idx][2], people) * v_o;
    }
    
    // Calculate objective = total_value - total_cost
    state.objective = total_value - total_cost;
    
    return state.objective;
}

// Strategy 1: GREEDY NEAREST-NEIGHBOR WITH DEMAND PRIORITIZATION (RECOMMENDED)
State generate_greedy_initial_state() {
    State state;
    state.helis.resize(H);
    
    // Calculate demand priority for each village (people * distance from nearest city)
    vector<pair<double, int>> village_priority;
    for (int v = 0; v < V; v++) {
        double min_dist = INFINITY;
        for (int c = 0; c < C; c++) {
            double dist = calculate_distance(cities[c], {villages[v].x, villages[v].y});
            min_dist = min(min_dist, dist);
        }
        // Priority = demand / accessibility (higher = more urgent)
        double priority = (villages[v].n * 9.0) / (min_dist + 1.0);
        village_priority.push_back({priority, v});
    }
    sort(village_priority.rbegin(), village_priority.rend()); // Descending priority
    
    vector<bool> village_served(V, false);
    
    for (int h = 0; h < H; h++) {
        pair<double, double> home_pos = cities[helis[h].home_city - 1];
        
        while (true) {
            // Find nearest unserved village from current position
            int best_village = -1;
            double best_distance = INFINITY;
            
            for (auto& [priority, v] : village_priority) {
                if (village_served[v]) continue;
                
                pair<double, double> village_pos = {villages[v].x, villages[v].y};
                double dist = calculate_distance(home_pos, village_pos);
                
                if (dist < best_distance) {
                    best_distance = dist;
                    best_village = v;
                }
            }
            
            if (best_village == -1) break; // No more villages
            
            // Create a trip to this village
            Trip trip;
            
            // Calculate optimal package allocation
            int people = villages[best_village].n;
            int food_needed = people * 9;
            int other_needed = people * 1;
            
            // Maximize value: prefer perishable food
            int perishable_packets = min(food_needed, (int)(helis[h].w_cap / w_p));
            int remaining_food = food_needed - perishable_packets;
            
            double remaining_capacity = helis[h].w_cap - perishable_packets * w_p;
            int dry_packets = min(remaining_food, (int)(remaining_capacity / w_d));
            
            remaining_capacity -= dry_packets * w_d;
            int other_packets = min(other_needed, (int)(remaining_capacity / w_o));
            
            // Check if trip is feasible
            double trip_dist = 2 * calculate_distance(home_pos, {villages[best_village].x, villages[best_village].y});
            if (trip_dist <= helis[h].dcap && 
                (perishable_packets * w_p + dry_packets * w_d + other_packets * w_o) <= helis[h].w_cap) {
                
                Delivery delivery = {best_village + 1, dry_packets, perishable_packets, other_packets}; // 1-indexed
                trip.stops.push_back(delivery);
                state.helis[h].trips.push_back(trip);
            }
            
            village_served[best_village] = true;
        }
    }
    
    return state;
}

// Strategy 2: CAPACITY-BASED CLUSTERING
State generate_cluster_initial_state() {
    State state;
    state.helis.resize(H);
    
    // Assign villages to helicopters based on distance to home cities
    vector<vector<int>> heli_villages(H);
    
    for (int v = 0; v < V; v++) {
        double best_distance = INFINITY;
        int best_heli = 0;
        
        for (int h = 0; h < H; h++) {
            pair<double, double> home_pos = cities[helis[h].home_city - 1];
            pair<double, double> village_pos = {villages[v].x, villages[v].y};
            double dist = calculate_distance(home_pos, village_pos);
            
            if (dist < best_distance) {
                best_distance = dist;
                best_heli = h;
            }
        }
        heli_villages[best_heli].push_back(v);
    }
    
    // Create trips for each helicopter
    for (int h = 0; h < H; h++) {
        if (heli_villages[h].empty()) continue;
        
        // Sort villages by distance from home
        pair<double, double> home_pos = cities[helis[h].home_city - 1];
        sort(heli_villages[h].begin(), heli_villages[h].end(), 
             [&](int v1, int v2) {
                 double d1 = calculate_distance(home_pos, {villages[v1].x, villages[v1].y});
                 double d2 = calculate_distance(home_pos, {villages[v2].x, villages[v2].y});
                 return d1 < d2;
             });
        
        // Create single-village trips (simple approach)
        for (int v : heli_villages[h]) {
            Trip trip;
            
            // Simple allocation: try to meet basic needs
            int people = villages[v].n;
            int food_packets = min(people * 9, (int)(helis[h].w_cap / w_p));
            int other_packets = min(people * 1, (int)((helis[h].w_cap - food_packets * w_p) / w_o));
            
            Delivery delivery = {v + 1, 0, food_packets, other_packets}; // 1-indexed, prefer perishable
            trip.stops.push_back(delivery);
            state.helis[h].trips.push_back(trip);
        }
    }
    
    return state;
}

// Strategy 3: SIMPLE ROUND-ROBIN (Fallback)
State generate_simple_initial_state() {
    State state;
    state.helis.resize(H);
    
    // Assign villages to helicopters in round-robin fashion
    for (int v = 0; v < V; v++) {
        int h = v % H; // Simple round-robin assignment
        
        Trip trip;
        
        // Basic package allocation
        int people = villages[v].n;
        double max_weight = helis[h].w_cap;
        
        // Try to allocate optimally within weight limits
        int perishable = min(people * 9, (int)(max_weight / (2 * w_p))); // Leave room for other
        int other = min(people * 1, (int)((max_weight - perishable * w_p) / w_o));
        
        Delivery delivery = {v + 1, 0, perishable, other}; // 1-indexed
        trip.stops.push_back(delivery);
        state.helis[h].trips.push_back(trip);
    }
    
    return state;
}

// Strategy 4: DEMAND-WEIGHTED INITIALIZATION
State generate_demand_weighted_initial_state() {
    State state;
    state.helis.resize(H);
    
    // Calculate total demand
    double total_demand = 0;
    for (int v = 0; v < V; v++) {
        total_demand += villages[v].n * 9; // Food demand
    }
    
    // Calculate helicopter capacity ratios
    double total_capacity = 0;
    for (int h = 0; h < H; h++) {
        total_capacity += helis[h].w_cap;
    }
    
    // Assign villages proportionally
    vector<bool> assigned(V, false);
    for (int h = 0; h < H; h++) {
        double heli_ratio = helis[h].w_cap / total_capacity;
        double target_demand = total_demand * heli_ratio;
        double current_demand = 0;
        
        pair<double, double> home_pos = cities[helis[h].home_city - 1];
        
        // Find nearest villages until capacity is roughly matched
        while (current_demand < target_demand) {
            int best_village = -1;
            double best_distance = INFINITY;
            
            for (int v = 0; v < V; v++) {
                if (assigned[v]) continue;
                
                pair<double, double> village_pos = {villages[v].x, villages[v].y};
                double dist = calculate_distance(home_pos, village_pos);
                
                if (dist < best_distance) {
                    best_distance = dist;
                    best_village = v;
                }
            }
            
            if (best_village == -1) break;
            
            // Create trip for this village
            Trip trip;
            int people = villages[best_village].n;
            int food_needed = people * 9;
            current_demand += food_needed;
            
            // Allocate packages
            int perishable = min(food_needed, (int)(helis[h].w_cap / w_p));
            int other = min(people, (int)((helis[h].w_cap - perishable * w_p) / w_o));
            
            Delivery delivery = {best_village + 1, 0, perishable, other}; // 1-indexed
            trip.stops.push_back(delivery);
            state.helis[h].trips.push_back(trip);
            
            assigned[best_village] = true;
        }
    }
    
    return state;
}




void two_opt_people_weighted(vector<int>& trip_villages, int home_city) {
    bool improved=true;
    while(improved){
        improved=false;
        for(int i=0;i+2<(int)trip_villages.size();i++){
            for(int j=i+2;j+1<(int)trip_villages.size();j++){
                int a=trip_villages[i], b=trip_villages[i+1];
                int c=trip_villages[j], d=trip_villages[j+1];
                auto home=cities[home_city-1];

                auto getPos=[&](int idx)->pair<double,double>{
                    if (idx<0) return home;
                    if (idx>=(int)trip_villages.size()) return home;
                    return {villages[trip_villages[idx]].x,villages[trip_villages[idx]].y};
                };
                pair<double,double> A=getPos(i),B=getPos(i+1),C=getPos(j),D=getPos(j+1);
                double pa = max(1,villages[b].n);
                double pb = max(1,villages[d].n);

                double oldcost = calculate_distance(A,B)/pa + calculate_distance(C,D)/pb;
                double newcost = calculate_distance(A,C)/pa + calculate_distance(B,D)/pb;

                if(newcost<oldcost){
                    reverse(trip_villages.begin()+i+1,trip_villages.begin()+j+1);
                    improved=true;
                }
            }
        }
    }
}



// -----------------------------------
// Randomized initial state generator
// -----------------------------------

State generate_randomized_initial_state() {
    State state;
    state.helis.resize(H);

    vector<int> order(V);
    iota(order.begin(), order.end(), 0);
    random_shuffle(order.begin(), order.end());

    for (int h=0; h<H; h++) {
        vector<int> assigned;
        for (int v: order) if (rand()%H==h) assigned.push_back(v);
        if (assigned.empty()) continue;

        random_shuffle(assigned.begin(),assigned.end());

        vector<vector<int>> trips;
        vector<int> cur;
        double cap=0;
        for (int v: assigned) {
            if (cap > helis[h].w_cap*0.8 && !cur.empty()) {
                trips.push_back(cur); cur.clear(); cap=0;
            }
            cur.push_back(v);
            cap += villages[v].n*5;
        }
        if (!cur.empty()) trips.push_back(cur);

        for (auto& tv: trips) {
            two_opt_people_weighted(tv, helis[h].home_city);

            Trip trip;
            double cap_left = helis[h].w_cap;
            for (int v: tv) {
                int people=villages[v].n;
                int food_need=9*people, other_need=people;
                int p = min(food_need,(int)(cap_left/w_p));
                cap_left -= p*w_p; food_need -= p;
                int d = min(food_need,(int)(cap_left/w_d));
                cap_left -= d*w_d;
                int o = min(other_need,(int)(cap_left/w_o));
                cap_left -= o*w_o;
                if(p+d+o>0) trip.stops.push_back({v+1,d,p,o});
                if(cap_left<=0) break;
            }
            fill_trip_data(h,trip);
            state.helis[h].trips.push_back(trip);
        }
        fill_helicopter_data(state.helis[h]);
    }
    fill_delivered_totals(state);
    obj_func(state);
    return state;
}


// RECOMMENDED: Use Strategy 1 (Greedy Nearest-Neighbor with Demand Prioritization)
State generate_initial_state() {
    // check objective function from all start states and use the best one
    State best_state = generate_greedy_initial_state();
    double best_objective = obj_func(best_state);

    State current_state;

    current_state = generate_cluster_initial_state();
    double current_objective = obj_func(current_state);
    if (current_objective > best_objective) {
        best_objective = current_objective;
        best_state = current_state;
    }

    current_state = generate_simple_initial_state();
    current_objective = obj_func(current_state);
    if (current_objective > best_objective) {
        best_objective = current_objective;
        best_state = current_state;
    }

    current_state = generate_demand_weighted_initial_state();
    current_objective = obj_func(current_state);
    if (current_objective > best_objective) {
        best_objective = current_objective;
        best_state = current_state;
    }

    return best_state;
}

//Generate neighbours (simple)

double village_value(int v_idx, const array<int,3>& delivered) {
    int people = villages[v_idx].n;
    int food_limit = 9 * people;

    int perishable = delivered[1];
    int dry        = delivered[0];
    int other      = delivered[2];

    int total_food = perishable + dry;
    int useful_food = min(total_food, food_limit);

    double val = 0.0;
    if (useful_food <= perishable) {
        val += useful_food * v_p;
    } else {
        val += perishable * v_p;
        val += (useful_food - perishable) * v_d;
    }
    val += min(other, people) * v_o;

    return val;
}

double trip_cost(const Trip& trip, int heli_id) {
    if (trip.stops.empty()) return 0.0;
    return helis[heli_id].F + helis[heli_id].alpha * trip.distance;
}

State neighbor_swap_villages(const State& state) {
    State new_state = state;

    int h1 = rand() % H, h2 = rand() % H;
    if (h1 == h2) return new_state;

    if (new_state.helis[h1].trips.empty() || new_state.helis[h2].trips.empty()) 
        return new_state;

    Trip& trip1 = new_state.helis[h1].trips[rand() % new_state.helis[h1].trips.size()];
    Trip& trip2 = new_state.helis[h2].trips[rand() % new_state.helis[h2].trips.size()];
    if (trip1.stops.empty() || trip2.stops.empty()) return new_state;

    int i1 = rand() % trip1.stops.size();
    int i2 = rand() % trip2.stops.size();

    Delivery old1 = trip1.stops[i1];
    Delivery old2 = trip2.stops[i2];

    int v1 = old1.village - 1;
    int v2 = old2.village - 1;

    // -------- save old contributions --------
    double old_val_v1 = village_value(v1, new_state.delivered[v1]);
    double old_val_v2 = village_value(v2, new_state.delivered[v2]);
    double old_cost1 = trip_cost(trip1, h1);
    double old_cost2 = trip_cost(trip2, h2);

    // -------- update delivered totals --------
    auto adjust_delivered = [&](Delivery d, int sign) {
        new_state.delivered[d.village-1][0] += sign*d.d;
        new_state.delivered[d.village-1][1] += sign*d.p;
        new_state.delivered[d.village-1][2] += sign*d.o;
    };
    adjust_delivered(old1, -1);
    adjust_delivered(old2, -1);

    swap(trip1.stops[i1], trip2.stops[i2]);

    adjust_delivered(trip1.stops[i1], +1);
    adjust_delivered(trip2.stops[i2], +1);

    // -------- update trip distances incrementally --------
    auto update_trip_distance = [&](int h, Trip& trip, int idx, Delivery oldD, Delivery newD) {
        double delta = 0.0;
        pair<double,double> home = cities[helis[h].home_city-1];

        pair<double,double> prev = (idx==0) ? home : 
            make_pair(villages[trip.stops[idx-1].village-1].x, villages[trip.stops[idx-1].village-1].y);

        pair<double,double> next = (idx==trip.stops.size()-1) ? home :
            make_pair(villages[trip.stops[idx+1].village-1].x, villages[trip.stops[idx+1].village-1].y);

        auto pos_old = make_pair(villages[oldD.village-1].x, villages[oldD.village-1].y);
        auto pos_new = make_pair(villages[newD.village-1].x, villages[newD.village-1].y);

        delta -= calculate_distance(prev,pos_old) + calculate_distance(pos_old,next);
        delta += calculate_distance(prev,pos_new) + calculate_distance(pos_new,next);

        trip.distance += delta;
        return delta;
    };

    double delta1 = update_trip_distance(h1, trip1, i1, old1, trip1.stops[i1]);
    double delta2 = update_trip_distance(h2, trip2, i2, old2, trip2.stops[i2]);

    // -------- update trip value incrementally --------
    auto delivery_value = [&](Delivery d) {
        return d.d*v_d + d.p*v_p + d.o*v_o;
    };
    trip1.value += delivery_value(trip1.stops[i1]) - delivery_value(old1);
    trip2.value += delivery_value(trip2.stops[i2]) - delivery_value(old2);

    // -------- update trip weight incrementally --------
    auto delivery_weight = [&](Delivery d) {
        return d.d*w_d + d.p*w_p + d.o*w_o;
    };
    trip1.weight += delivery_weight(trip1.stops[i1]) - delivery_weight(old1);
    trip2.weight += delivery_weight(trip2.stops[i2]) - delivery_weight(old2);

    // -------- update heli total distances incrementally --------
    new_state.helis[h1].total_distance += delta1;
    new_state.helis[h2].total_distance += delta2;

    // -------- recompute only affected objective contributions --------
    double new_val_v1 = village_value(v1, new_state.delivered[v1]);
    double new_val_v2 = village_value(v2, new_state.delivered[v2]);
    double new_cost1 = trip_cost(trip1, h1);
    double new_cost2 = trip_cost(trip2, h2);

    new_state.objective = state.objective
                        - old_val_v1 - old_val_v2
                        + new_val_v1 + new_val_v2
                        - old_cost1 - old_cost2
                        + new_cost1 + new_cost2;

    return new_state;
}

State neighbor_reassign_village(const State& state) {
    State new_state = state;

    int h1 = rand() % H;
    if (new_state.helis[h1].trips.empty()) return new_state;

    Trip& trip1 = new_state.helis[h1].trips[rand() % new_state.helis[h1].trips.size()];
    if (trip1.stops.empty()) return new_state;

    int idx = rand() % trip1.stops.size();
    Delivery moved = trip1.stops[idx];
    int v = moved.village - 1;

    // -------- Save old contributions --------
    double old_val_v = village_value(v, new_state.delivered[v]);
    double old_cost1 = trip_cost(trip1, h1);
    double old_cost2 = 0.0;

    int h2 = rand() % H;
    if (h2 == h1 && new_state.helis[h1].trips.size() == 1 && trip1.stops.size() == 1)
        return new_state; // avoid degenerate

    Trip* trip2_ptr = nullptr;
    bool new_trip_created = false;
    if (new_state.helis[h2].trips.empty() || (rand()%2==0)) {
        // create new trip if none exists or sometimes randomly
        new_state.helis[h2].trips.push_back(Trip());
        trip2_ptr = &new_state.helis[h2].trips.back();
        new_trip_created = true;
    } else {
        trip2_ptr = &new_state.helis[h2].trips[rand() % new_state.helis[h2].trips.size()];
    }
    Trip& trip2 = *trip2_ptr;
    old_cost2 = trip_cost(trip2, h2);

    // -------- Update delivered totals --------
    new_state.delivered[v][0] -= moved.d;
    new_state.delivered[v][1] -= moved.p;
    new_state.delivered[v][2] -= moved.o;

    // -------- Update trip1 (remove delivery) --------
    {
        pair<double,double> home = cities[helis[h1].home_city-1];
        pair<double,double> prev = (idx==0) ? home : make_pair(villages[trip1.stops[idx-1].village-1].x, villages[trip1.stops[idx-1].village-1].y);
        pair<double,double> next = (idx==trip1.stops.size()-1) ? home : make_pair(villages[trip1.stops[idx+1].village-1].x, villages[trip1.stops[idx+1].village-1].y);
        auto pos_moved = make_pair(villages[moved.village-1].x, villages[moved.village-1].y);

        double delta = -calculate_distance(prev,pos_moved) - calculate_distance(pos_moved,next)
                       + calculate_distance(prev,next);
        trip1.distance += delta;
        new_state.helis[h1].total_distance += delta;
    }

    auto delivery_value = [&](const Delivery& d) {
        return d.d*v_d + d.p*v_p + d.o*v_o;
    };

    auto delivery_weight = [&](const Delivery& d) {
        return d.d*w_d + d.p*w_p + d.o*w_o;
    };

    trip1.value -= delivery_value(moved);
    trip1.weight -= delivery_weight(moved);

    trip1.stops.erase(trip1.stops.begin() + idx);

    // -------- Update trip2 (insert delivery) --------
    int pos = rand() % (trip2.stops.size() + 1);
    {
        pair<double,double> home = cities[helis[h2].home_city-1];
        pair<double,double> prev = (pos==0) ? home : make_pair(villages[trip2.stops[pos-1].village-1].x, villages[trip2.stops[pos-1].village-1].y);
        pair<double,double> next = (pos==trip2.stops.size()) ? home : make_pair(villages[trip2.stops[pos].village-1].x, villages[trip2.stops[pos].village-1].y);
        auto pos_moved = make_pair(villages[moved.village-1].x, villages[moved.village-1].y);

        double delta = -calculate_distance(prev,next)
                       + calculate_distance(prev,pos_moved) + calculate_distance(pos_moved,next);
        trip2.distance += delta;
        new_state.helis[h2].total_distance += delta;
    }

    trip2.stops.insert(trip2.stops.begin() + pos, moved);
    trip2.value += delivery_value(moved);
    trip2.weight += delivery_weight(moved);

    // -------- Update delivered totals again (for new placement) --------
    new_state.delivered[v][0] += moved.d;
    new_state.delivered[v][1] += moved.p;
    new_state.delivered[v][2] += moved.o;

    // -------- Recompute affected contributions incrementally --------
    double new_val_v = village_value(v, new_state.delivered[v]);
    double new_cost1 = trip_cost(trip1, h1);
    double new_cost2 = trip_cost(trip2, h2);

    new_state.objective = state.objective
                        - old_val_v + new_val_v
                        - old_cost1 - old_cost2
                        + new_cost1 + new_cost2;

    return new_state;
}



//2 opt method to optimise dcap thing
State neighbor_2opt(const State& state) {
    State new_state = state;

    int h = rand() % H;
    if (new_state.helis[h].trips.empty()) return new_state;

    Trip& trip = new_state.helis[h].trips[rand() % new_state.helis[h].trips.size()];
    int n = trip.stops.size();
    if (n < 4) return new_state; // 2-opt needs >= 4

    int i = rand() % (n - 1);
    int j = i + 1 + rand() % (n - i - 1);

    // -------- Save old trip cost --------
    double old_cost = trip_cost(trip, h);

    // -------- Compute distance delta --------
    pair<double,double> home = cities[helis[h].home_city-1];

    auto getPos = [&](int idx) {
        if (idx == -1) return home;
        if (idx == n) return home;
        return make_pair(villages[trip.stops[idx].village-1].x,
                         villages[trip.stops[idx].village-1].y);
    };

    pair<double,double> pi_1 = getPos(i-1);
    pair<double,double> pi   = getPos(i);
    pair<double,double> pj_1 = getPos(j-1);
    pair<double,double> pj   = getPos(j);

    double delta = 0.0;
    delta -= calculate_distance(pi_1, pi);
    delta -= calculate_distance(pj_1, pj);
    delta += calculate_distance(pi_1, pj_1);
    delta += calculate_distance(pi, pj);

    trip.distance += delta;
    new_state.helis[h].total_distance += delta;

    // -------- Apply the actual 2-opt reversal --------
    reverse(trip.stops.begin() + i, trip.stops.begin() + j);

    // -------- Update objective incrementally --------
    double new_cost = trip_cost(trip, h);
    new_state.objective = state.objective - old_cost + new_cost;

    return new_state;
}

State neighbor_swap_adjacent(const State& state) {
    State new_state = state;

    int h = rand() % H;
    if (new_state.helis[h].trips.empty()) return new_state;

    Trip& trip = new_state.helis[h].trips[rand() % new_state.helis[h].trips.size()];
    int n = trip.stops.size();
    if (n < 2) return new_state;

    int i = rand() % (n - 1);  // swap i and i+1
    Delivery& A = trip.stops[i];
    Delivery& B = trip.stops[i+1];

    // -------- Save old cost --------
    double old_cost = trip_cost(trip, h);

    // -------- Compute distance delta --------
    pair<double,double> home = cities[helis[h].home_city-1];
    auto getPos = [&](int idx) {
        if (idx == -1) return home;
        if (idx == n) return home;
        return make_pair(villages[trip.stops[idx].village-1].x,
                         villages[trip.stops[idx].village-1].y);
    };

    pair<double,double> prev = getPos(i-1);
    pair<double,double> next = getPos(i+2);

    auto posA = make_pair(villages[A.village-1].x, villages[A.village-1].y);
    auto posB = make_pair(villages[B.village-1].x, villages[B.village-1].y);

    double delta = 0.0;
    delta -= calculate_distance(prev, posA);
    delta -= calculate_distance(posA, posB);
    delta -= calculate_distance(posB, next);

    delta += calculate_distance(prev, posB);
    delta += calculate_distance(posB, posA);
    delta += calculate_distance(posA, next);

    trip.distance += delta;
    new_state.helis[h].total_distance += delta;

    // -------- Actually swap deliveries --------
    swap(A, B);

    // -------- Update objective incrementally --------
    double new_cost = trip_cost(trip, h);
    new_state.objective = state.objective - old_cost + new_cost;

    return new_state;
}

State neighbor_food_mix(const State& state) {
    State new_state = state;

    int h = rand() % H;
    if (new_state.helis[h].trips.empty()) return new_state;

    Trip& trip = new_state.helis[h].trips[rand() % new_state.helis[h].trips.size()];
    if (trip.stops.empty()) return new_state;

    int idx = rand() % trip.stops.size();
    Delivery& d = trip.stops[idx];
    int v = d.village - 1;

    // -------- Save old contributions --------
    double old_val_v = village_value(v, new_state.delivered[v]);
    double old_cost = trip_cost(trip, h); // cost doesn’t change, but we keep formality

    Delivery oldD = d;

    // -------- Apply modification --------
    if (d.d > 0) {
        d.d -= 1;
        d.p += 1;
    } else if (d.p > 0) {
        d.p -= 1;
        d.d += 1;
    } else {
        return new_state; // nothing to swap
    }

    // -------- Update delivered totals --------
    new_state.delivered[v][0] += (d.d - oldD.d);
    new_state.delivered[v][1] += (d.p - oldD.p);

    // -------- Update trip weight incrementally --------
    trip.weight += (d.d - oldD.d) * w_d + (d.p - oldD.p) * w_p;

    // -------- Update trip value incrementally --------
    trip.value += (d.d - oldD.d) * v_d + (d.p - oldD.p) * v_p;

    // -------- Recompute affected contributions --------
    double new_val_v = village_value(v, new_state.delivered[v]);
    double new_cost = trip_cost(trip, h); // unchanged

    new_state.objective = state.objective
                        - old_val_v + new_val_v
                        - old_cost + new_cost;  // effectively cancels, since cost same

    return new_state;
}


State neighbor_rebalance_other(const State& state) {
    State new_state = state;

    int h = rand() % H;
    if (new_state.helis[h].trips.empty()) return new_state;

    Trip& trip = new_state.helis[h].trips[rand() % new_state.helis[h].trips.size()];
    int n = trip.stops.size();
    if (n < 2) return new_state;

    int i = rand() % n;
    int j = (i + 1 + rand() % (n - 1)) % n;

    if (trip.stops[i].o == 0) return new_state; // nothing to move

    int vi = trip.stops[i].village - 1;
    int vj = trip.stops[j].village - 1;

    // -------- Save old contributions --------
    double old_val_i = village_value(vi, new_state.delivered[vi]);
    double old_val_j = village_value(vj, new_state.delivered[vj]);

    double old_cost = trip_cost(trip, h); // unchanged, but for consistency

    // -------- Apply modification --------
    trip.stops[i].o -= 1;
    trip.stops[j].o += 1;

    // -------- Update delivered totals --------
    new_state.delivered[vi][2] -= 1;
    new_state.delivered[vj][2] += 1;

    // -------- Recompute affected contributions --------
    double new_val_i = village_value(vi, new_state.delivered[vi]);
    double new_val_j = village_value(vj, new_state.delivered[vj]);
    double new_cost  = trip_cost(trip, h); // unchanged

    new_state.objective = state.objective
                        - old_val_i - old_val_j
                        + new_val_i + new_val_j
                        - old_cost + new_cost;

    return new_state;
}


// -----------------------------------
// Biased random choice
// -----------------------------------
int biased_random_choice(const vector<double>& weights) {
    double sum=0; for(auto w:weights) sum+=w;
    double r=((double)rand()/RAND_MAX)*sum;
    double cum=0;
    for(int i=0;i<(int)weights.size();i++){ cum+=weights[i]; if(r<=cum) return i;}
    return weights.size()-1;
}

State neighbor_remove_village(const State& state) {
    State new_state=state;
    vector<pair<int,int>> candidates;
    for(int h=0;h<H;h++) for(int t=0;t<(int)new_state.helis[h].trips.size();t++)
        if(!new_state.helis[h].trips[t].stops.empty()) candidates.push_back({h,t});
    if(candidates.empty()) return new_state;

    vector<double> weights;
    vector<pair<int,int>> chosen;
    for(auto [h,t]:candidates){
        auto& trip=new_state.helis[h].trips[t];
        auto& d=trip.stops[rand()%trip.stops.size()];
        int v=d.village-1;
        weights.push_back(1.0/(1.0+village_value(v,new_state.delivered[v])));
        chosen.push_back({h,t});
    }
    int idx=biased_random_choice(weights);
    auto [h,t]=chosen[idx];
    Trip& trip=new_state.helis[h].trips[t];
    int i=rand()%trip.stops.size();
    Delivery d=trip.stops[i]; int v=d.village-1;

    double old_val=village_value(v,new_state.delivered[v]);
    double old_cost=trip_cost(trip,h);

    new_state.delivered[v][0]-=d.d;
    new_state.delivered[v][1]-=d.p;
    new_state.delivered[v][2]-=d.o;

    pair<double,double> home=cities[helis[h].home_city-1];
    pair<double,double> prev=(i==0)?home:make_pair(villages[trip.stops[i-1].village-1].x,villages[trip.stops[i-1].village-1].y);
    pair<double,double> next=(i==trip.stops.size()-1)?home:make_pair(villages[trip.stops[i+1].village-1].x,villages[trip.stops[i+1].village-1].y);
    auto posd=make_pair(villages[d.village-1].x,villages[d.village-1].y);
    double delta=-calculate_distance(prev,posd)-calculate_distance(posd,next)+calculate_distance(prev,next);
    trip.distance+=delta; new_state.helis[h].total_distance+=delta;

    trip.value-=d.d*v_d+d.p*v_p+d.o*v_o;
    trip.weight-=d.d*w_d+d.p*w_p+d.o*w_o;

    trip.stops.erase(trip.stops.begin()+i);
    if(trip.stops.empty()) new_state.helis[h].trips.erase(new_state.helis[h].trips.begin()+t);

    double new_val=village_value(v,new_state.delivered[v]);
    double new_cost=(trip.stops.empty()?0.0:trip_cost(trip,h));
    new_state.objective=state.objective-old_val+new_val-old_cost+new_cost;
    return new_state;
}

State neighbor_add_village(const State& state) {
    State new_state=state;
    vector<int> candidates; vector<double> weights;
    for(int v=0;v<V;v++) if(new_state.delivered[v][0]+new_state.delivered[v][1]+new_state.delivered[v][2]==0) {
        candidates.push_back(v); weights.push_back(villages[v].n);
    }
    if(candidates.empty()) return new_state;
    int v=candidates[biased_random_choice(weights)];
    int h=rand()%H;

    Trip* trip_ptr;
    if(new_state.helis[h].trips.empty()||rand()%2==0){new_state.helis[h].trips.push_back(Trip()); trip_ptr=&new_state.helis[h].trips.back();}
    else trip_ptr=&new_state.helis[h].trips[rand()%new_state.helis[h].trips.size()];
    Trip& trip=*trip_ptr;

    double cap_left=helis[h].w_cap-trip.weight;
    if(cap_left<=0) return new_state;
    int people=villages[v].n; int food_need=9*people, other_need=people;

    int p=min(food_need,(int)(cap_left/w_p)); cap_left-=p*w_p; food_need-=p;
    int d=min(food_need,(int)(cap_left/w_d)); cap_left-=d*w_d;
    int o=min(other_need,(int)(cap_left/w_o)); cap_left-=o*w_o;
    if(p+d+o==0) return new_state;

    Delivery dnew={v+1,d,p,o};
    double old_val=village_value(v,new_state.delivered[v]);
    double old_cost=trip_cost(trip,h);

    int pos=rand()%(trip.stops.size()+1);
    pair<double,double> home=cities[helis[h].home_city-1];
    pair<double,double> prev=(pos==0)?home:make_pair(villages[trip.stops[pos-1].village-1].x,villages[trip.stops[pos-1].village-1].y);
    pair<double,double> next=(pos==trip.stops.size())?home:make_pair(villages[trip.stops[pos].village-1].x,villages[trip.stops[pos].village-1].y);
    auto posd=make_pair(villages[dnew.village-1].x,villages[dnew.village-1].y);
    double delta=-calculate_distance(prev,next)+calculate_distance(prev,posd)+calculate_distance(posd,next);
    trip.distance+=delta; new_state.helis[h].total_distance+=delta;

    trip.stops.insert(trip.stops.begin()+pos,dnew);
    trip.value+=dnew.d*v_d+dnew.p*v_p+dnew.o*v_o;
    trip.weight+=dnew.d*w_d+dnew.p*w_p+dnew.o*w_o;
    new_state.delivered[v][0]+=dnew.d; new_state.delivered[v][1]+=dnew.p; new_state.delivered[v][2]+=dnew.o;

    double new_val=village_value(v,new_state.delivered[v]);
    double new_cost=trip_cost(trip,h);
    new_state.objective=state.objective-old_val+new_val-old_cost+new_cost;
    return new_state;
}

State generate_random_neighbor(const State& current) {
    int choice = rand()%7; // 7 neighbors now
    switch(choice){
        case 0: return neighbor_reassign_village(current);
        case 1: return neighbor_2opt(current);
        case 2: return neighbor_swap_adjacent(current);
        case 3: return neighbor_food_mix(current);
        case 4: return neighbor_rebalance_other(current);
        case 5: return neighbor_remove_village(current);
        case 6: return neighbor_add_village(current);
    }
    return current;
}

// ---------- Hill climbing with random restarts + patience ----------
State hill_climb_with_random_restart(int max_restarts, int patience, int neighbor_samples) {
    State best_state;
    best_state.objective = -INFINITY;

    for (int r = 0; r < max_restarts; r++) {
        // start from randomized initial
        State current = generate_randomized_initial_state();
        obj_func(current);

        int no_improve = 0;
        while (no_improve < patience) {
            State best_neighbor = current;
            bool improved = false;

            // sample multiple neighbors, pick best
            for (int s = 0; s < neighbor_samples; s++) {
                State neighbor = generate_random_neighbor(current);
                if (neighbor.objective > best_neighbor.objective) {
                    best_neighbor = neighbor;
                    improved = true;
                }
            }

            if (improved) {
                current = best_neighbor;
                no_improve = 0;
            } else {
                no_improve++;
            }
        }

        if (current.objective > best_state.objective) {
            best_state = current;
        }
    }
    return best_state;
}

// Function to print state in the specified output format
void print_state_solution(const State& state, ostream& out = cout) {
    for (int h = 0; h < H; h++) {
        const Helicopter& heli = state.helis[h];
        
        out << h + 1 << " " << heli.trips.size() << endl;
        
        for (const Trip& trip : heli.trips) {
            int total_d = 0, total_p = 0, total_o = 0;
            for (const Delivery& delivery : trip.stops) {
                total_d += delivery.d;
                total_p += delivery.p;
                total_o += delivery.o;
            }
            
            out << total_d << " " << total_p << " " << total_o << " ";
            
            out << trip.stops.size() << " ";
            
            for (const Delivery& delivery : trip.stops) {
                out << delivery.village << " " << delivery.d << " " << delivery.p << " " << delivery.o << " ";
            }
            out << endl;
        }
        
        out << -1 << endl;
    }
}

int main(){
    double time;
    cin >> time;

    cin >> DMax;

    cin >> w_d >> v_d >> w_p >> v_p >> w_o >> v_o;

    cin >> C;
    cities.resize(C);
    for (int i = 0; i < C; ++i) {
        double x, y;
        cin >> x >> y;
        cities[i] = {x, y};
    }

    cin >> V;
    villages.resize(V);
    for (int i = 0; i < V; ++i) {
        double x, y;
        int n;
        cin >> x >> y >> n;
        villages[i] = {x, y, n};
    }

    cin >> H;
    helis.resize(H);
    for (int i = 0; i < H; ++i) {
        int home_city;
        double wcap, dcap, F, alpha;
        cin >> home_city >> wcap >> dcap >> F >> alpha;
        helis[i] = {home_city, wcap, dcap, F, alpha};
    }

    precompute_distances();

    // Example usage:
    State test_state;
    test_state.helis.resize(H);
    
    // Initialize with empty trips
    for (int h = 0; h < H; h++) {
        test_state.helis[h].trips.clear();
        test_state.helis[h].total_distance = 0.0;
    }
    

    State best = hill_climb_with_random_restart(10, 100, 50); // 10 restarts, patience=100
    print_state_solution(best);
    cout << "Final Objective value: " << best.objective << endl;

    State initial_state = generate_initial_state();
    print_state_solution(initial_state);
    // Calculate objective (this will fill all the missing fields)
    double result = obj_func(initial_state);

    cout << "Objective value: " << result << endl;
    
    // Create state from the example output
    State state;
    state.helis.resize(H);
    
    // Helicopter 1, Trip 1@
    Trip trip1;
    Delivery delivery1_1 = {1, 8890, 111, 0}; // Village 1
    //Delivery delivery1_2 = {2, 8910, 96, 269};    // Village 2
    trip1.stops.push_back(delivery1_1);
    //trip1.stops.push_back(delivery1_2);
    
    // Helicopter 1, Trip 2
    Trip trip2;
    Delivery delivery2_1 = {2, 8890, 111, 0};  // Village 2
    trip2.stops.push_back(delivery2_1);
    
    // Add trips to helicopter 1
    state.helis[0].trips.push_back(trip1);
    state.helis[0].trips.push_back(trip2);

    double result2 = obj_func(state);
    cout << "Objective value (state): " << result2 << endl;
    
    // Print the state in the required format
    //cout << "\nExample output in required format:" << endl;
    //print_state_solution(state);
    
    return 0;
}