#include <iostream>
#include <vector>
#include <array>
#include <map>
#include <cmath>
#include <algorithm>

using namespace std;

struct Village {
    double x;
    double y;
    int n;
};

struct Helicopter_info {
    int home_city;
    double w_cap, dcap, F, alpha;
};

struct Delivery {
    int village;
    int d, p, o; // packets dropped
};

struct Trip {
    vector<Delivery> stops;   // villages visited in order
    double distance;          // cached route length
    double value;             // cached total value
    double weight;            // total carried weight
};

struct Helicopter {
    vector<Trip> trips;       // all trips (some may be empty)
    double total_distance;    // sum of trip distances
};

struct State {
    vector<Helicopter> helis; 
    vector<array<int,3>> delivered; // per-village totals (d,p,o)
    double objective;         // cached objective value
};

// Global variables for problem parameters
double DMax;
double w_d, v_d, w_p, v_p, w_o, v_o;
vector<pair<double, double>> cities;
vector<Village> villages;
vector<Helicopter_info> helis;
int C, V, H;

double calculate_distance(pair<double, double> p1, pair<double, double> p2) {
    return sqrt((p1.first - p2.first) * (p1.first - p2.first) + 
                (p1.second - p2.second) * (p1.second - p2.second));
}

// Calculate the total distance for a trip route (home -> villages -> home)
double calculate_trip_distance(int heli_id, const Trip& trip) {
    if (trip.stops.empty()) return 0.0;
    
    double total_dist = 0.0;
    pair<double, double> current_pos = cities[helis[heli_id].home_city - 1]; // Start at home city (1-indexed)
    
    // Visit each village in order
    for (const Delivery& delivery : trip.stops) {
        pair<double, double> village_pos = {villages[delivery.village - 1].x, villages[delivery.village - 1].y}; // 1-indexed
        total_dist += calculate_distance(current_pos, village_pos);
        current_pos = village_pos;
    }
    
    // Return to home city
    total_dist += calculate_distance(current_pos, cities[helis[heli_id].home_city - 1]);
    
    return total_dist;
}

// Calculate the total weight of packages carried in a trip
double calculate_trip_weight(const Trip& trip) {
    if (trip.stops.empty()) return 0.0;
    
    double max_weight = 0.0;
    map<int, array<int,3>> remaining_to_deliver;
    
    // First pass: calculate total packages to pick up
    for (const Delivery& delivery : trip.stops) {
        remaining_to_deliver[delivery.village][0] += delivery.d;
        remaining_to_deliver[delivery.village][1] += delivery.p;
        remaining_to_deliver[delivery.village][2] += delivery.o;
    }
    
    array<int,3> current_load = {0, 0, 0};
    
    // Calculate initial load (total packages to carry)
    for (const auto& pair : remaining_to_deliver) {
        current_load[0] += pair.second[0];
        current_load[1] += pair.second[1];
        current_load[2] += pair.second[2];
    }
    
    double current_weight = current_load[0] * w_d + current_load[1] * w_p + current_load[2] * w_o;
    max_weight = max(max_weight, current_weight);
    
    // Simulate the trip to find maximum weight carried
    for (const Delivery& delivery : trip.stops) {
        // Drop packages at this village
        current_load[0] -= delivery.d;
        current_load[1] -= delivery.p;
        current_load[2] -= delivery.o;
        
        current_weight = current_load[0] * w_d + current_load[1] * w_p + current_load[2] * w_o;
        max_weight = max(max_weight, current_weight);
    }
    
    return max_weight;
}

// Calculate the value generated by a trip
double calculate_trip_value(const Trip& trip) {
    double trip_value = 0.0;
    
    for (const Delivery& delivery : trip.stops) {
        trip_value += delivery.d * v_d + delivery.p * v_p + delivery.o * v_o;
    }
    
    return trip_value;
}

// Fill all Trip fields (distance, weight, value)
void fill_trip_data(int heli_id, Trip& trip) {
    trip.distance = calculate_trip_distance(heli_id, trip);
    trip.weight = calculate_trip_weight(trip);
    trip.value = calculate_trip_value(trip);
}

// Fill helicopter total_distance
void fill_helicopter_data(Helicopter& heli) {
    heli.total_distance = 0.0;
    for (const Trip& trip : heli.trips) {
        heli.total_distance += trip.distance;
    }
}

// Fill the delivered array with totals per village
void fill_delivered_totals(State& state) {
    // Initialize delivered array
    state.delivered.assign(V, {0, 0, 0});
    
    // Sum up deliveries from all helicopters and trips
    for (const Helicopter& heli : state.helis) {
        for (const Trip& trip : heli.trips) {
            for (const Delivery& delivery : trip.stops) {
                state.delivered[delivery.village - 1][0] += delivery.d; // Convert to 0-indexed
                state.delivered[delivery.village - 1][1] += delivery.p;
                state.delivered[delivery.village - 1][2] += delivery.o;
            }
        }
    }
}

double obj_func(State& state) {
    // Fill all missing data
    for (int h = 0; h < H; h++) {
        for (Trip& trip : state.helis[h].trips) {
            fill_trip_data(h, trip);
        }
        fill_helicopter_data(state.helis[h]);
    }
    
    fill_delivered_totals(state);
    
    double total_value = 0.0;
    double total_cost = 0.0;
    
    // Check feasibility constraints first
    for (int h = 0; h < H; h++) {
        const Helicopter& heli = state.helis[h];
        
        // Check if total distance exceeds DMax
        if (heli.total_distance > DMax + 1e-9) {
            state.objective = -INFINITY;
            return -INFINITY; // Infeasible
        }
        
        for (const Trip& trip : heli.trips) {
            if (trip.stops.empty()) continue; // Skip empty trips
            
            // Check weight capacity constraint
            if (trip.weight > helis[h].w_cap + 1e-9) {
                state.objective = -INFINITY;
                return -INFINITY; // Infeasible
            }
            
            // Check distance capacity constraint per trip
            if (trip.distance > helis[h].dcap + 1e-9) {
                state.objective = -INFINITY;
                return -INFINITY; // Infeasible
            }
            
            // Add trip cost
            total_cost += helis[h].F + helis[h].alpha * trip.distance;
        }
    }
    
    // Calculate total value from deliveries
    for (int v_idx = 0; v_idx < V; v_idx++) {
        int people = villages[v_idx].n;
        int food_limit = 9 * people; // Maximum useful food packets
        
        // Calculate food delivered (d + p)
        int total_food = state.delivered[v_idx][0] + state.delivered[v_idx][1];
        int useful_food = min(total_food, food_limit);
        
        // Calculate value from food (prioritize perishable over dry)
        int perishable = state.delivered[v_idx][1];
        int dry = state.delivered[v_idx][0];
        
        if (useful_food <= perishable) {
            // All useful food is perishable
            total_value += useful_food * v_p; // perishable value
        } else {
            // Use all perishable + some dry
            total_value += perishable * v_p; // all perishable
            total_value += (useful_food - perishable) * v_d; // remaining as dry
        }
        
        // Add value from other supplies (no limit specified in problem)
        total_value += state.delivered[v_idx][2] * v_o;
    }
    
    // Calculate objective = total_value - total_cost
    state.objective = total_value - total_cost;
    
    return state.objective;
}

// Strategy 1: GREEDY NEAREST-NEIGHBOR WITH DEMAND PRIORITIZATION (RECOMMENDED)
State generate_greedy_initial_state() {
    State state;
    state.helis.resize(H);
    
    // Calculate demand priority for each village (people * distance from nearest city)
    vector<pair<double, int>> village_priority;
    for (int v = 0; v < V; v++) {
        double min_dist = INFINITY;
        for (int c = 0; c < C; c++) {
            double dist = calculate_distance(cities[c], {villages[v].x, villages[v].y});
            min_dist = min(min_dist, dist);
        }
        // Priority = demand / accessibility (higher = more urgent)
        double priority = (villages[v].n * 9.0) / (min_dist + 1.0);
        village_priority.push_back({priority, v});
    }
    sort(village_priority.rbegin(), village_priority.rend()); // Descending priority
    
    vector<bool> village_served(V, false);
    
    for (int h = 0; h < H; h++) {
        pair<double, double> home_pos = cities[helis[h].home_city - 1];
        
        while (true) {
            // Find nearest unserved village from current position
            int best_village = -1;
            double best_distance = INFINITY;
            
            for (auto& [priority, v] : village_priority) {
                if (village_served[v]) continue;
                
                pair<double, double> village_pos = {villages[v].x, villages[v].y};
                double dist = calculate_distance(home_pos, village_pos);
                
                if (dist < best_distance) {
                    best_distance = dist;
                    best_village = v;
                }
            }
            
            if (best_village == -1) break; // No more villages
            
            // Create a trip to this village
            Trip trip;
            
            // Calculate optimal package allocation
            int people = villages[best_village].n;
            int food_needed = people * 9;
            int other_needed = people * 1;
            
            // Maximize value: prefer perishable food
            int perishable_packets = min(food_needed, (int)(helis[h].w_cap / w_p));
            int remaining_food = food_needed - perishable_packets;
            
            double remaining_capacity = helis[h].w_cap - perishable_packets * w_p;
            int dry_packets = min(remaining_food, (int)(remaining_capacity / w_d));
            
            remaining_capacity -= dry_packets * w_d;
            int other_packets = min(other_needed, (int)(remaining_capacity / w_o));
            
            // Check if trip is feasible
            double trip_dist = 2 * calculate_distance(home_pos, {villages[best_village].x, villages[best_village].y});
            if (trip_dist <= helis[h].dcap && 
                (perishable_packets * w_p + dry_packets * w_d + other_packets * w_o) <= helis[h].w_cap) {
                
                Delivery delivery = {best_village + 1, dry_packets, perishable_packets, other_packets}; // 1-indexed
                trip.stops.push_back(delivery);
                state.helis[h].trips.push_back(trip);
            }
            
            village_served[best_village] = true;
        }
    }
    
    return state;
}

// Strategy 2: CAPACITY-BASED CLUSTERING
State generate_cluster_initial_state() {
    State state;
    state.helis.resize(H);
    
    // Assign villages to helicopters based on distance to home cities
    vector<vector<int>> heli_villages(H);
    
    for (int v = 0; v < V; v++) {
        double best_distance = INFINITY;
        int best_heli = 0;
        
        for (int h = 0; h < H; h++) {
            pair<double, double> home_pos = cities[helis[h].home_city - 1];
            pair<double, double> village_pos = {villages[v].x, villages[v].y};
            double dist = calculate_distance(home_pos, village_pos);
            
            if (dist < best_distance) {
                best_distance = dist;
                best_heli = h;
            }
        }
        heli_villages[best_heli].push_back(v);
    }
    
    // Create trips for each helicopter
    for (int h = 0; h < H; h++) {
        if (heli_villages[h].empty()) continue;
        
        // Sort villages by distance from home
        pair<double, double> home_pos = cities[helis[h].home_city - 1];
        sort(heli_villages[h].begin(), heli_villages[h].end(), 
             [&](int v1, int v2) {
                 double d1 = calculate_distance(home_pos, {villages[v1].x, villages[v1].y});
                 double d2 = calculate_distance(home_pos, {villages[v2].x, villages[v2].y});
                 return d1 < d2;
             });
        
        // Create single-village trips (simple approach)
        for (int v : heli_villages[h]) {
            Trip trip;
            
            // Simple allocation: try to meet basic needs
            int people = villages[v].n;
            int food_packets = min(people * 9, (int)(helis[h].w_cap / w_p));
            int other_packets = min(people * 1, (int)((helis[h].w_cap - food_packets * w_p) / w_o));
            
            Delivery delivery = {v + 1, 0, food_packets, other_packets}; // 1-indexed, prefer perishable
            trip.stops.push_back(delivery);
            state.helis[h].trips.push_back(trip);
        }
    }
    
    return state;
}

// Strategy 3: SIMPLE ROUND-ROBIN (Fallback)
State generate_simple_initial_state() {
    State state;
    state.helis.resize(H);
    
    // Assign villages to helicopters in round-robin fashion
    for (int v = 0; v < V; v++) {
        int h = v % H; // Simple round-robin assignment
        
        Trip trip;
        
        // Basic package allocation
        int people = villages[v].n;
        double max_weight = helis[h].w_cap;
        
        // Try to allocate optimally within weight limits
        int perishable = min(people * 9, (int)(max_weight / (2 * w_p))); // Leave room for other
        int other = min(people * 1, (int)((max_weight - perishable * w_p) / w_o));
        
        Delivery delivery = {v + 1, 0, perishable, other}; // 1-indexed
        trip.stops.push_back(delivery);
        state.helis[h].trips.push_back(trip);
    }
    
    return state;
}

// Strategy 4: DEMAND-WEIGHTED INITIALIZATION
State generate_demand_weighted_initial_state() {
    State state;
    state.helis.resize(H);
    
    // Calculate total demand
    double total_demand = 0;
    for (int v = 0; v < V; v++) {
        total_demand += villages[v].n * 9; // Food demand
    }
    
    // Calculate helicopter capacity ratios
    double total_capacity = 0;
    for (int h = 0; h < H; h++) {
        total_capacity += helis[h].w_cap;
    }
    
    // Assign villages proportionally
    vector<bool> assigned(V, false);
    for (int h = 0; h < H; h++) {
        double heli_ratio = helis[h].w_cap / total_capacity;
        double target_demand = total_demand * heli_ratio;
        double current_demand = 0;
        
        pair<double, double> home_pos = cities[helis[h].home_city - 1];
        
        // Find nearest villages until capacity is roughly matched
        while (current_demand < target_demand) {
            int best_village = -1;
            double best_distance = INFINITY;
            
            for (int v = 0; v < V; v++) {
                if (assigned[v]) continue;
                
                pair<double, double> village_pos = {villages[v].x, villages[v].y};
                double dist = calculate_distance(home_pos, village_pos);
                
                if (dist < best_distance) {
                    best_distance = dist;
                    best_village = v;
                }
            }
            
            if (best_village == -1) break;
            
            // Create trip for this village
            Trip trip;
            int people = villages[best_village].n;
            int food_needed = people * 9;
            current_demand += food_needed;
            
            // Allocate packages
            int perishable = min(food_needed, (int)(helis[h].w_cap / w_p));
            int other = min(people, (int)((helis[h].w_cap - perishable * w_p) / w_o));
            
            Delivery delivery = {best_village + 1, 0, perishable, other}; // 1-indexed
            trip.stops.push_back(delivery);
            state.helis[h].trips.push_back(trip);
            
            assigned[best_village] = true;
        }
    }
    
    return state;
}

// RECOMMENDED: Use Strategy 1 (Greedy Nearest-Neighbor with Demand Prioritization)
State generate_initial_state() {
    // check objective function from all start states and use the best one
    State best_state = generate_greedy_initial_state();
    double best_objective = obj_func(best_state);

    State current_state;

    current_state = generate_cluster_initial_state();
    double current_objective = obj_func(current_state);
    if (current_objective > best_objective) {
        best_objective = current_objective;
        best_state = current_state;
    }

    current_state = generate_simple_initial_state();
    current_objective = obj_func(current_state);
    if (current_objective > best_objective) {
        best_objective = current_objective;
        best_state = current_state;
    }

    current_state = generate_demand_weighted_initial_state();
    current_objective = obj_func(current_state);
    if (current_objective > best_objective) {
        best_objective = current_objective;
        best_state = current_state;
    }

    return best_state;
}

//Generate neighbours (simple)

State neighbor_swap_villages(const State& state) {
    State new_state = state;

    // pick two random helicopters
    int h1 = rand() % H;
    int h2 = rand() % H;
    if (h1 == h2) return new_state;

    // pick random trip and random village from each
    if (new_state.helis[h1].trips.empty() || new_state.helis[h2].trips.empty()) 
        return new_state;

    Trip& trip1 = new_state.helis[h1].trips[rand() % new_state.helis[h1].trips.size()];
    Trip& trip2 = new_state.helis[h2].trips[rand() % new_state.helis[h2].trips.size()];
    if (trip1.stops.empty() || trip2.stops.empty()) return new_state;

    int i1 = rand() % trip1.stops.size();
    int i2 = rand() % trip2.stops.size();

    // swap deliveries
    swap(trip1.stops[i1], trip2.stops[i2]);

    return new_state;
}

State neighbor_reassign_village(const State& state) {
    State new_state = state;

    int h1 = rand() % H;
    if (new_state.helis[h1].trips.empty()) return new_state;

    Trip& trip1 = new_state.helis[h1].trips[rand() % new_state.helis[h1].trips.size()];
    if (trip1.stops.empty()) return new_state;

    int idx = rand() % trip1.stops.size();
    Delivery moved = trip1.stops[idx];
    trip1.stops.erase(trip1.stops.begin() + idx);

    int h2 = rand() % H;
    Trip& trip2 = new_state.helis[h2].trips[rand() % (new_state.helis[h2].trips.size() + 1)];

    // insert at random position
    int pos = rand() % (trip2.stops.size() + 1);
    trip2.stops.insert(trip2.stops.begin() + pos, moved);

    return new_state;
}


//2 opt method to optimise dcap thing
State neighbor_2opt(const State& state) {
    State new_state = state;

    int h = rand() % H;
    if (new_state.helis[h].trips.empty()) return new_state;

    Trip& trip = new_state.helis[h].trips[rand() % new_state.helis[h].trips.size()];
    if (trip.stops.size() < 4) return new_state; // 2-opt needs >= 4

    int i = rand() % (trip.stops.size() - 1);
    int j = i + 1 + rand() % (trip.stops.size() - i - 1);

    reverse(trip.stops.begin() + i, trip.stops.begin() + j);

    return new_state;
}

State neighbor_swap_adjacent(const State& state) {
    State new_state = state;

    int h = rand() % H;
    if (new_state.helis[h].trips.empty()) return new_state;

    Trip& trip = new_state.helis[h].trips[rand() % new_state.helis[h].trips.size()];
    if (trip.stops.size() < 2) return new_state;

    int i = rand() % (trip.stops.size() - 1);
    swap(trip.stops[i], trip.stops[i+1]);

    return new_state;
}

State neighbor_food_mix(const State& state) {
    State new_state = state;

    int h = rand() % H;
    if (new_state.helis[h].trips.empty()) return new_state;

    Trip& trip = new_state.helis[h].trips[rand() % new_state.helis[h].trips.size()];
    if (trip.stops.empty()) return new_state;

    Delivery& d = trip.stops[rand() % trip.stops.size()];

    if (d.d > 0) {
        d.d -= 1;
        d.p += 1; // trade dry for perishable
    } else if (d.p > 0) {
        d.p -= 1;
        d.d += 1; // trade perishable for dry
    }

    return new_state;
}

State neighbor_rebalance_other(const State& state) {
    State new_state = state;

    int h = rand() % H;
    if (new_state.helis[h].trips.empty()) return new_state;

    Trip& trip = new_state.helis[h].trips[rand() % new_state.helis[h].trips.size()];
    if (trip.stops.size() < 2) return new_state;

    int i = rand() % trip.stops.size();
    int j = (i + 1 + rand() % (trip.stops.size() - 1)) % trip.stops.size();

    if (trip.stops[i].o > 0) {
        trip.stops[i].o -= 1;
        trip.stops[j].o += 1;
    }

    return new_state;
}


// Function to print state in the specified output format
void print_state_solution(const State& state, ostream& out = cout) {
    for (int h = 0; h < H; h++) {
        const Helicopter& heli = state.helis[h];
        
        out << h + 1 << " " << heli.trips.size() << endl;
        
        for (const Trip& trip : heli.trips) {
            int total_d = 0, total_p = 0, total_o = 0;
            for (const Delivery& delivery : trip.stops) {
                total_d += delivery.d;
                total_p += delivery.p;
                total_o += delivery.o;
            }
            
            out << total_d << " " << total_p << " " << total_o << " ";
            
            out << trip.stops.size() << " ";
            
            for (const Delivery& delivery : trip.stops) {
                out << delivery.village << " " << delivery.d << " " << delivery.p << " " << delivery.o << " ";
            }
            out << endl;
        }
        
        out << -1 << endl;
    }
}

int main(){
    double time;
    cin >> time;

    cin >> DMax;

    cin >> w_d >> v_d >> w_p >> v_p >> w_o >> v_o;

    cin >> C;
    cities.resize(C);
    for (int i = 0; i < C; ++i) {
        double x, y;
        cin >> x >> y;
        cities[i] = {x, y};
    }

    cin >> V;
    villages.resize(V);
    for (int i = 0; i < V; ++i) {
        double x, y;
        int n;
        cin >> x >> y >> n;
        villages[i] = {x, y, n};
    }

    cin >> H;
    helis.resize(H);
    for (int i = 0; i < H; ++i) {
        int home_city;
        double wcap, dcap, F, alpha;
        cin >> home_city >> wcap >> dcap >> F >> alpha;
        helis[i] = {home_city, wcap, dcap, F, alpha};
    }

    // Example usage:
    State test_state;
    test_state.helis.resize(H);
    
    // Initialize with empty trips
    for (int h = 0; h < H; h++) {
        test_state.helis[h].trips.clear();
        test_state.helis[h].total_distance = 0.0;
    }
    
    State initial_state = generate_initial_state();
    print_state_solution(initial_state);
    // Calculate objective (this will fill all the missing fields)
    double result = obj_func(initial_state);

    cout << "Objective value: " << result << endl;
    
    // Create state from the example output
    State state;
    state.helis.resize(H);
    
    // Helicopter 1, Trip 1@
    Trip trip1;
    Delivery delivery1_1 = {1, 9000, 0, 1000}; // Village 1
    Delivery delivery1_2 = {2, 0, 0, 1000};    // Village 2
    trip1.stops.push_back(delivery1_1);
    trip1.stops.push_back(delivery1_2);
    
    // Helicopter 1, Trip 2
    Trip trip2;
    Delivery delivery2_1 = {2, 8889, 111, 0};  // Village 2
    trip2.stops.push_back(delivery2_1);
    
    // Add trips to helicopter 1
    state.helis[0].trips.push_back(trip1);
    state.helis[0].trips.push_back(trip2);

    double result2 = obj_func(state);
    cout << "Objective value (state): " << result2 << endl;
    
    // Print the state in the required format
    cout << "\nExample output in required format:" << endl;
    print_state_solution(state);
    
    return 0;
}